# Generated by Django 4.2.18 on 2025-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=123, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
