# Generated by Django 4.2.18 on 2025-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjueta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="category",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
